using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NTG.Agent.Common.Dtos.Agents;
using NTG.Agent.Common.Dtos.Chats;
using NTG.Agent.Orchestrator.Agents;
using NTG.Agent.Orchestrator.Data;
using NTG.Agent.Orchestrator.Dtos;
using NTG.Agent.Orchestrator.Extentions;

namespace NTG.Agent.Orchestrator.Controllers;

[Route("api/[controller]")]
[ApiController]
public class AgentsController : ControllerBase
{
    private readonly AgentService _agentService;
    private readonly AgentDbContext _agentDbContext;
    public AgentsController(AgentService agentService, AgentDbContext agentDbContext)
    {
        _agentService = agentService ?? throw new ArgumentNullException(nameof(agentService));
        _agentDbContext = agentDbContext;
    }

    /// <summary>
    /// Streams chat responses asynchronously based on the provided prompt request.
    /// </summary>
    /// <remarks>The method retrieves the user ID from the current context and streams responses generated by
    /// the agent service. Ensure that the <paramref name="promptRequest"/> contains valid data to avoid
    /// errors.</remarks>
    /// <param name="promptRequest">The prompt request containing the input data for generating chat responses.</param>
    /// <returns>An asynchronous stream of <see cref="PromptResponse"/> objects, each representing a response to the prompt.</returns>
    [HttpPost("chat")]
    public async IAsyncEnumerable<PromptResponse> ChatAsync([FromForm] PromptRequestForm promptRequest)
    {
        Guid? userId = User.GetUserId();
        await foreach (var response in _agentService.ChatStreamingAsync(userId, promptRequest))
        {
            yield return new PromptResponse(response);
        }
    }

    /// <summary>
    /// Retrieves a list of agents that are marked as published.
    /// </summary>
    /// <remarks>The method returns a collection of agents, each represented as a data transfer object 
    /// containing the agent's ID, name, and default status. Only agents with the <see cref="Agent.IsPublished"/> 
    /// property set to <see langword="true"/> are included in the result.</remarks>
    /// <returns>An <see cref="IActionResult"/> containing an HTTP 200 OK response with a list of <see cref="AgentListItemDto"/>
    /// objects. The list will be empty if no published agents are found.</returns>
    [HttpGet]
    public async Task<IActionResult> GetAgents()
    {
        var agents = await _agentDbContext.Agents
            .Where(a => a.IsPublished)
            .Select(a => new AgentListItemDto(a.Id, a.Name, a.IsDefault))
            .ToListAsync();
        return Ok(agents);
    }
}
