using NTG.Agent.Common.Dtos.Chats;
using System.Net.Http.Json;
using NTG.Agent.WebClient.Client.Dtos;
using System.Globalization;
using NTG.Agent.Common.Dtos.Agents;
using NTG.Agent.Common.Dtos;

namespace NTG.Agent.WebClient.Client.Services;

public class ChatClient(HttpClient httpClient)
{
    private const string REQUEST_URI = "/api/agents/chat";

    private const int MAX_FILES_SIZE = 50 * 1024 * 1024; // 50 MB

    // Returning IAsyncEnumerable (not Task<IAsyncEnumerable>) keeps `form` and `response` in scope
    // for the entire iteration, avoiding premature disposal of the response stream.
    // HttpCompletionOption.ResponseHeadersRead enables true streaming: chunks arrive as they are
    // generated by the LLM instead of waiting for the full response to buffer.
    public async IAsyncEnumerable<PromptResponse> InvokeStreamAsync(
        PromptRequest<UploadItemClient> request,
        [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        // Validate that the total size of all documents does not exceed the limit.
        if (request.Documents != null)
        {
            var totalSize = request.Documents.Sum(d => d.Size);
            if (totalSize > MAX_FILES_SIZE)
            {
                throw new InvalidOperationException(
                    $"Total upload size ({totalSize / (1024 * 1024.0):F1} MB) exceeds the maximum allowed size of {MAX_FILES_SIZE / (1024 * 1024)} MB.");
            }
        }

        using var form = new MultipartFormDataContent();

        // --- 1️ Add Documents first ---
        if (request.Documents != null)
        {
            for (int i = 0; i < request.Documents.Count(); i++)
            {
                var doc = request.Documents.ElementAt(i);

                // File content
                if (doc.Content != null)
                {
                    form.Add(doc.Content, $"{nameof(request.Documents)}[{i}].{nameof(doc.Content)}", doc.Name);
                }

                // Scalars inside document
                form.Add(new StringContent(doc.Name ?? ""), $"{nameof(request.Documents)}[{i}].{nameof(doc.Name)}");
                form.Add(new StringContent(doc.Status.ToString()), $"{nameof(request.Documents)}[{i}].{nameof(doc.Status)}");
                form.Add(new StringContent(doc.Message ?? ""), $"{nameof(request.Documents)}[{i}].{nameof(doc.Message)}");
                form.Add(new StringContent(doc.Progress.ToString(CultureInfo.InvariantCulture)), $"{nameof(request.Documents)}[{i}].{nameof(doc.Progress)}");
            }
        }

        // --- 2️ Add other scalar properties ---
        form.Add(new StringContent(request.Prompt ?? ""), nameof(request.Prompt));
        form.Add(new StringContent(request.ConversationId.ToString()), nameof(request.ConversationId));
        if (!string.IsNullOrEmpty(request.SessionId))
            form.Add(new StringContent(request.SessionId), nameof(request.SessionId));
        form.Add(new StringContent(request.AgentId.ToString()), nameof(request.AgentId));

        // --- 3️ Send request, reading headers-first so the response can be streamed ---
        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, REQUEST_URI) { Content = form };
        using var response = await httpClient.SendAsync(httpRequest, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
        response.EnsureSuccessStatusCode();

        var stream = response.Content.ReadFromJsonAsAsyncEnumerable<PromptResponse>(cancellationToken: cancellationToken);
        if (stream is null) yield break;

        await foreach (var item in stream)
        {
            if (item is not null)
                yield return item;
        }
    }

    public async Task<List<AgentListItemDto>> GetAgentsAsync()
    {
        var response = await httpClient.GetAsync("/api/agents");
        response.EnsureSuccessStatusCode();
        var agents = await response.Content.ReadFromJsonAsync<List<AgentListItemDto>>();
        return agents ?? new List<AgentListItemDto>();
    }

    /// <summary>
    /// Retrieves server-side feature flags so the UI can conditionally show or hide features
    /// such as the file upload button, which requires Azure Document Intelligence to be configured.
    /// </summary>
    public async Task<FeatureFlagsDto> GetFeaturesAsync()
    {
        var response = await httpClient.GetAsync("/api/features");
        response.EnsureSuccessStatusCode();
        return await response.Content.ReadFromJsonAsync<FeatureFlagsDto>()
               ?? new FeatureFlagsDto(DocumentIntelligenceEnabled: false);
    }

}
